##!/bin/sh
#
#gnupginf="${HOME}/.gpg-agent-info"
#
#if pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
#	eval $(cat $gnupginf)
#	eval $(cut -d= -f1 $gnupginf | xargs echo export)
#else
#	eval $(gpg-agent --quiet --daemon --enable-ssh-support --write-env-file "$gnupginf")
#fi


xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap

exec awesome

#eval $(gpg-agent -s --enable-ssh-support --daemon)
#eval $(gpg-agent -s --enable-ssh-support --daemon --write-env-file "$gnupginf")
