xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap

systemctl --user start ssh-agent
systemctl --user start gpg-agent

# https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart
# systemctl --user start gpg-agent

if [ -f $HOME/.xinitrc.local ];
then
	$HOME/.xinitrc.local
fi

xautolock -time 10 -secure -locker "/usr/bin/xlock -mode blank" -notify 30 -notifier "notify-send --urgency=normal --expire-time=10000 'Locking in 30 secs'" &

exec awesome
